# Assignment 1: Numpy

Perform the follwing tasks:


In [3]:
#3.1: import the numpy library
import numpy as np

In [13]:
#3.2: create a random 10x10 array named A
A = np.random.rand(10,10)

#Mit nefativen Werten
#np.random.randn(10,10)
A

array([[0.30281316, 0.22569912, 0.26180465, 0.20820493, 0.69326852,
        0.68216565, 0.46217977, 0.88228934, 0.34471998, 0.72044778],
       [0.85227274, 0.17003341, 0.03238353, 0.52022426, 0.64339588,
        0.3881954 , 0.21475435, 0.71966323, 0.65856851, 0.75825542],
       [0.13543033, 0.90538161, 0.22325404, 0.50349038, 0.81176198,
        0.97691766, 0.35072383, 0.29607283, 0.00579543, 0.736864  ],
       [0.39550451, 0.46612967, 0.55322736, 0.49043633, 0.95110339,
        0.82241694, 0.44717653, 0.24282562, 0.94044978, 0.99525639],
       [0.63043856, 0.42524847, 0.58422713, 0.70074235, 0.16327107,
        0.19218286, 0.27339754, 0.00926851, 0.43442191, 0.76997686],
       [0.0406735 , 0.94973146, 0.47960472, 0.52561935, 0.93616283,
        0.76567845, 0.26461627, 0.11587953, 0.09871763, 0.6549111 ],
       [0.33281335, 0.63560657, 0.71712624, 0.26320032, 0.70910526,
        0.23670225, 0.53990235, 0.24785685, 0.20058771, 0.80888479],
       [0.23331672, 0.55117572, 0.1067868

In [14]:
#3.3: return only the odd rows of A
A[::2]

array([[0.30281316, 0.22569912, 0.26180465, 0.20820493, 0.69326852,
        0.68216565, 0.46217977, 0.88228934, 0.34471998, 0.72044778],
       [0.13543033, 0.90538161, 0.22325404, 0.50349038, 0.81176198,
        0.97691766, 0.35072383, 0.29607283, 0.00579543, 0.736864  ],
       [0.63043856, 0.42524847, 0.58422713, 0.70074235, 0.16327107,
        0.19218286, 0.27339754, 0.00926851, 0.43442191, 0.76997686],
       [0.33281335, 0.63560657, 0.71712624, 0.26320032, 0.70910526,
        0.23670225, 0.53990235, 0.24785685, 0.20058771, 0.80888479],
       [0.61864995, 0.3223942 , 0.06905445, 0.90765826, 0.29356601,
        0.57844117, 0.44832976, 0.76187776, 0.87889187, 0.98747113]])

In [20]:
#3.4: perform a matrix multiplication of A with it's transposed
MA = np.matrix(A)

MA.T * MA

matrix([[1.99990924, 1.52280065, 1.14384394, 2.05443235, 2.00140698,
         1.82090952, 1.4554274 , 1.865647  , 2.23794159, 2.95738532],
        [1.52280065, 3.41806311, 2.00957084, 2.4905627 , 3.44320464,
         3.20075056, 2.17458493, 1.93093184, 2.09502471, 3.7107868 ],
        [1.14384394, 2.00957084, 1.67379939, 1.46351497, 2.19542405,
         1.69525415, 1.37111534, 1.05422783, 1.45241119, 2.5105858 ],
        [2.05443235, 2.4905627 , 1.46351497, 2.93653826, 2.69816794,
         2.97506598, 2.04773821, 2.05036917, 2.57920829, 3.82006368],
        [2.00140698, 3.44320464, 2.19542405, 2.69816794, 4.29536657,
         3.77422047, 2.42705769, 2.55118278, 2.66296267, 4.48503457],
        [1.82090952, 3.20075056, 1.69525415, 2.97506598, 3.77422047,
         4.06134178, 2.50028277, 2.51037616, 2.65611872, 4.29976671],
        [1.4554274 , 2.17458493, 1.37111534, 2.04773821, 2.42705769,
         2.50028277, 1.96874147, 1.92506488, 2.1157623 , 3.03197775],
        [1.865647  , 1.9309

In [21]:
#3.5: compute the matrix inverse of A
M.I

matrix([[-0.09941564,  1.50355874,  1.22463406, -0.14473875,  1.42743722,
         -1.45520319, -0.52673745,  0.53720219, -1.96788621,  0.27233   ],
        [-1.27582199, -0.22625884,  1.96709309, -0.04506996, -0.13828233,
         -1.19914368,  0.21538297, -0.41513728,  0.32900942,  1.17605766],
        [ 2.10229648, -0.75111308, -1.55302136, -0.20560674,  2.04629086,
          1.36102669, -1.3110117 ,  0.03024231, -1.10668513,  0.25993315],
        [ 0.38298573,  0.47174393, -3.02345092, -1.22863583,  0.13291779,
          3.48517366, -0.37647866,  0.83058659,  0.51135697, -0.95097459],
        [-0.3803698 ,  1.35345483, -1.85443089, -0.1303992 , -1.27661285,
          2.06764185,  0.75959228,  0.46293463, -0.32184979, -0.72064545],
        [ 1.2576357 , -0.39037453,  1.26733986,  0.57079681,  1.51540825,
         -0.94348984, -1.88332719,  0.25446751, -1.35649522,  0.18002105],
        [-0.65440783,  0.51914842, -0.51792123, -0.35752614, -0.80168835,
         -0.47091781,  1.7667543

In [24]:
#3.6: divide all entries of A which are lager than 0.5 by 2 (hint: use where() )
mask = (0.5 < A)
#mask
A[mask] /2

array([0.34663426, 0.34108282, 0.44114467, 0.36022389, 0.42613637,
       0.26011213, 0.32169794, 0.35983161, 0.32928425, 0.37912771,
       0.45269081, 0.25174519, 0.40588099, 0.48845883, 0.368432  ,
       0.27661368, 0.4755517 , 0.41120847, 0.47022489, 0.49762819,
       0.31521928, 0.29211356, 0.35037118, 0.38498843, 0.47486573,
       0.26280968, 0.46808142, 0.38283923, 0.32745555, 0.31780328,
       0.35856312, 0.35455263, 0.26995117, 0.40444239, 0.27558786,
       0.34079444, 0.44315772, 0.39937624, 0.26476163, 0.33471978,
       0.29857496, 0.30932497, 0.45382913, 0.28922059, 0.38093888,
       0.43944594, 0.49373556, 0.31885122, 0.32865279, 0.31622008])

In [25]:
A #Änderungen nicht übernommen!?

array([[0.30281316, 0.22569912, 0.26180465, 0.20820493, 0.69326852,
        0.68216565, 0.46217977, 0.88228934, 0.34471998, 0.72044778],
       [0.85227274, 0.17003341, 0.03238353, 0.52022426, 0.64339588,
        0.3881954 , 0.21475435, 0.71966323, 0.65856851, 0.75825542],
       [0.13543033, 0.90538161, 0.22325404, 0.50349038, 0.81176198,
        0.97691766, 0.35072383, 0.29607283, 0.00579543, 0.736864  ],
       [0.39550451, 0.46612967, 0.55322736, 0.49043633, 0.95110339,
        0.82241694, 0.44717653, 0.24282562, 0.94044978, 0.99525639],
       [0.63043856, 0.42524847, 0.58422713, 0.70074235, 0.16327107,
        0.19218286, 0.27339754, 0.00926851, 0.43442191, 0.76997686],
       [0.0406735 , 0.94973146, 0.47960472, 0.52561935, 0.93616283,
        0.76567845, 0.26461627, 0.11587953, 0.09871763, 0.6549111 ],
       [0.33281335, 0.63560657, 0.71712624, 0.26320032, 0.70910526,
        0.23670225, 0.53990235, 0.24785685, 0.20058771, 0.80888479],
       [0.23331672, 0.55117572, 0.1067868